soru2

In [1]:
import numpy as np
liste=[2,5,6,1,6,8,9,12,45,65]
array_list=np.array(liste)
array_list

array([ 2,  5,  6,  1,  6,  8,  9, 12, 45, 65])

soru3

In [2]:
np.zeros((10,10),dtype="int32")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

soru4

In [3]:
np.ones((10,10),dtype="float32")

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

soru5

In [4]:
np.full((10,10),9,dtype="int32")

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

soru6

In [5]:
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

 soru7

In [6]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

soru8

In [7]:
np.random.randint(0,30,(5,6))

array([[15, 19, 15, 20,  2, 22],
       [18, 14,  7, 28,  5, 26],
       [24, 15, 13,  1,  1, 25],
       [ 2, 21, 12, 23,  8,  2],
       [15, 28, 29, 28, 22,  1]])

soru9

In [8]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

soru10

In [9]:
a=np.random.randint(0,10,size=(5,10))
print(a)
print("eleman sayisi:",a.size)
print("boyut sayisi:",a.ndim)
print("matris tipi",a.shape)
print(a.dtype)

[[1 5 1 0 8 5 0 6 3 8]
 [2 6 3 5 7 4 4 7 7 2]
 [4 2 2 9 2 2 0 7 5 8]
 [2 2 3 0 9 2 5 4 6 3]
 [2 2 0 7 4 9 0 7 1 5]]
eleman sayisi: 50
boyut sayisi: 2
matris tipi (5, 10)
int32


soru11

In [10]:
np.random.randint(0,10,size=(3,4,7))

array([[[6, 3, 9, 1, 0, 9, 4],
        [6, 5, 7, 8, 7, 5, 5],
        [5, 1, 1, 0, 2, 0, 5],
        [9, 1, 0, 4, 3, 0, 4]],

       [[9, 8, 6, 0, 8, 9, 7],
        [3, 3, 0, 4, 0, 9, 8],
        [4, 7, 9, 7, 2, 8, 1],
        [6, 7, 8, 5, 2, 8, 7]],

       [[8, 6, 9, 8, 4, 5, 8],
        [4, 6, 4, 2, 7, 0, 0],
        [2, 8, 2, 3, 7, 7, 7],
        [6, 3, 9, 4, 4, 1, 7]]])

soru12

In [11]:
a=np.array([2,4,5,12,54,9,0,23,67,45])
array_1=a.reshape(2,5)
array_2=a.reshape(1,10)
print(a)          #orjinal array (vektor)
print(array_1)   #(2x5) lik matris tipi
print(array_2)   #(1x10) luk matris

[ 2  4  5 12 54  9  0 23 67 45]
[[ 2  4  5 12 54]
 [ 9  0 23 67 45]]
[[ 2  4  5 12 54  9  0 23 67 45]]


soru13

In [12]:
list_of_array=[]   #arrayleri bir listede toplasak
for i in range(4):
    a=np.random.randint(0,10,7,dtype="int32")    #vektor tipinde bir array
    list_of_array.append(a)
sonuc=np.concatenate([list_of_array[0],list_of_array[2],list_of_array[2],list_of_array[3]])
print(sonuc)

#####eger (1xn) tipinde bir matris olsaydi birlesimine bakalim
print("########")

list_of_array=[]   #arrayleri bir listede toplasak
for i in range(4):
    a=np.random.randint(0,10,size=(1,6),dtype="int32")    #(1x6) tipinde bir matris array
    list_of_array.append(a)
sonuc_2=np.concatenate([list_of_array[0],list_of_array[2],list_of_array[2],list_of_array[3]])
print(sonuc_2)

[5 6 6 0 2 6 3 8 6 7 7 4 3 1 8 6 7 7 4 3 1 1 1 2 3 2 8 5]
########
[[5 1 2 7 4 4]
 [9 9 9 8 3 6]
 [9 9 9 8 3 6]
 [9 0 7 7 2 6]]


soru14

In [13]:
a=np.array([1,6,5,1,2,9])
b=np.array([2,4,5,9,6,5])
a=a.reshape(2,3)
b=b.reshape(2,3)

print(np.concatenate([a,b]))   #default axis=0 satirlar halinde birlestiriyor
print("####")
print(np.concatenate([a,b],axis=0))  #axis=0 satirlar halinde birlestiriyor
print("####")
print(np.concatenate([a,b],axis=1))   #sutunlar halinde birlestiriyor

[[1 6 5]
 [1 2 9]
 [2 4 5]
 [9 6 5]]
####
[[1 6 5]
 [1 2 9]
 [2 4 5]
 [9 6 5]]
####
[[1 6 5 2 4 5]
 [1 2 9 9 6 5]]


soru15

axis=0 satir anlatiyor axis=1 sutun anlatiyor

soru16

In [14]:
a=np.random.randint(1,4,(3,6),dtype="int32")
b=np.random.randint(5,8,(3,4),dtype="int32")
print(np.concatenate([a,b],axis=1)) #satir sayisi ayni oldugu icin yan yana yani sutunlar olarak birlestirdik axis=1

[[3 3 3 2 1 3 7 6 6 5]
 [3 3 1 2 1 1 7 5 7 5]
 [1 2 3 1 1 3 7 6 5 5]]


In [15]:
a=np.random.randint(1,4,(3,6),dtype="int32")
b=np.random.randint(5,8,(5,6),dtype="int32")
print(np.concatenate([a,b],axis=0)) #sutun sayisi ayni oldugu icin alt alta yani sutunlar olarak birlestirdik axis=0

[[2 1 2 2 3 1]
 [3 2 2 1 2 1]
 [2 1 3 2 2 1]
 [5 7 6 5 6 5]
 [6 7 5 7 7 6]
 [7 7 7 7 7 5]
 [6 7 7 6 5 6]
 [6 7 7 6 7 5]]


soru17
10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [16]:
a=[1,2,3,4,5,6,7,8,9,10]
array=np.split(a,[2,5,7])
array

[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([ 8,  9, 10])]

soru18

Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [17]:
array1=np.random.randint(1,26,12,dtype="int32")
array2=np.sort(array1)
print(array1)
print(array2)
nerede=np.argsort(array1)
print(nerede)

[16 20 25  2  9 13  3 10 11 24  1 16]
[ 1  2  3  9 10 11 13 16 16 20 24 25]
[10  3  6  4  7  8  5  0 11  1  9  2]


soru19

20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [18]:
arry=np.random.randint(1,37,20,dtype="int32")
print(arry)
print(arry[3])
print(arry[5])
print(arry[7])

[16 24  5 34  3 34 34 35 15 36 18  4 15  5 24 14 24  3 15  8]
34
34
35


soru20

10 elemanli random bir vektor olusturunuz ve bu arrayin4. elemanini farkli bir sayiyla degistiriniz

In [19]:
arry=np.random.randint(1,37,10,dtype="int32")
print(arry)
arry[4]=77
print(arry)

[16 22 29 34 15 34  8  9 21 15]
[16 22 29 34 77 34  8  9 21 15]


soru21

“Diagonal Matrix” ve “Trace Matrix”kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

diagonal matris:asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise 

trace matrix:(matrisin izi) bir kare matrisin köşegen üzerindeki elemanlarının toplamıdır. 

soru 22

5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [20]:
arry=np.random.randint(1,20,size=(5,5),dtype="int32")

In [21]:
arry

array([[ 3, 12, 16, 13,  6],
       [15, 12,  1, 10,  2],
       [ 4,  3,  9,  1,  3],
       [11, 14, 17, 15, 18],
       [11,  7, 18,  6, 10]])

In [22]:
for i in range(5):
    print(arry[i][i])

3
12
9
15
10


soru 23:10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [23]:
arry=np.random.randint(1,9,15,dtype="int32")
print(arry)
arry[3:]

[5 6 6 5 4 5 6 8 2 5 3 4 2 8 7]


array([5, 4, 5, 6, 8, 2, 5, 3, 4, 2, 8, 7])

soru 24: 10X10 luk bir matris olusturunuz ve ;.3.satir ve 5.sutuna ulasiniz.

In [24]:
arry=np.random.randint(0,8,size=(10,10),dtype="int32")
print(arry)
print(arry[3])
print(arry[5])

[[5 7 7 4 0 6 1 0 3 7]
 [7 3 1 0 2 1 0 3 1 1]
 [7 3 0 0 7 6 1 0 5 6]
 [2 4 6 7 7 2 5 1 2 2]
 [3 5 5 3 1 2 6 7 3 3]
 [6 4 2 4 2 3 4 5 6 4]
 [1 0 4 7 1 4 2 1 5 0]
 [0 2 3 3 3 5 7 4 0 6]
 [6 7 2 3 1 4 3 3 0 7]
 [1 5 6 2 3 0 1 6 7 7]]
[2 4 6 7 7 2 5 1 2 2]
[6 4 2 4 2 3 4 5 6 4]


24a : 5.sutunun tum satirlarina ulasiniz.

In [25]:
arry[:,5]

array([6, 1, 6, 2, 2, 3, 4, 5, 4, 0])

b: Tum sutunlarin2.satirlarina ulasiniz.

In [26]:
print(arry[2])
print(arry[2,:])


[7 3 0 0 7 6 1 0 5 6]
[7 3 0 0 7 6 1 0 5 6]


24c: tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz

In [27]:
arry[2:7]

array([[7, 3, 0, 0, 7, 6, 1, 0, 5, 6],
       [2, 4, 6, 7, 7, 2, 5, 1, 2, 2],
       [3, 5, 5, 3, 1, 2, 6, 7, 3, 3],
       [6, 4, 2, 4, 2, 3, 4, 5, 6, 4],
       [1, 0, 4, 7, 1, 4, 2, 1, 5, 0]])

24d : satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz

In [28]:
arry[2:5,3:7]

array([[0, 7, 6, 1],
       [7, 7, 2, 5],
       [3, 1, 2, 6]])

24e : satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz

In [29]:
arry[5:,:4]

array([[6, 4, 2, 4],
       [1, 0, 4, 7],
       [0, 2, 3, 3],
       [6, 7, 2, 3],
       [1, 5, 6, 2]])

24 f : sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.

In [30]:
arry[:,3:10:3]

array([[4, 1, 7],
       [0, 0, 1],
       [0, 1, 6],
       [7, 5, 2],
       [3, 6, 3],
       [4, 4, 4],
       [7, 2, 0],
       [3, 7, 6],
       [3, 3, 7],
       [2, 1, 7]])

24 g : 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz

In [31]:
arry[5][5]=1986
print(arry)

[[   5    7    7    4    0    6    1    0    3    7]
 [   7    3    1    0    2    1    0    3    1    1]
 [   7    3    0    0    7    6    1    0    5    6]
 [   2    4    6    7    7    2    5    1    2    2]
 [   3    5    5    3    1    2    6    7    3    3]
 [   6    4    2    4    2 1986    4    5    6    4]
 [   1    0    4    7    1    4    2    1    5    0]
 [   0    2    3    3    3    5    7    4    0    6]
 [   6    7    2    3    1    4    3    3    0    7]
 [   1    5    6    2    3    0    1    6    7    7]]


soru 25: 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin

In [35]:
arry=np.arange(0,50,5,dtype="int32")
matrs=arry.reshape(1,10)
matrs

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45]])

.20 den buyuk olan kac deger var.
a.30’dan kucuk kac deger var
b.icerisinde 33 gecen kac deger var

In [36]:
a=np.sum(matrs>20)
a

5

In [37]:
k=np.sum(matrs<30)
k

6

In [38]:
e=np.sum(matrs==33)
e

0

c.olusturulan arrayin tum elemanlarini 5 ile carpin.d.olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.e.olustural arrayin icerisinde, sadece sutunlara bakarak her bir sutunu toplayin ve toplami 30 dan buyuk kac sutun varf.olustural arrayin icerisinde, sadece satirlara bakarak her bir satiri toplayin ve toplami 30 dan buyuk kac satir var

In [40]:
matrs*5

array([[  0,  25,  50,  75, 100, 125, 150, 175, 200, 225]])

In [41]:
matrs%2

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

In [62]:

np.add.accumulate(matrs)

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45]], dtype=int32)

In [63]:

np.add.accumulate(matrs,axis=1)

array([[  0,   5,  15,  30,  50,  75, 105, 140, 180, 225]], dtype=int32)

soru 26: 0 ile 1 arasinda50 elamanli bir array olusturunuz ve;.orlamasini aliniz.a.standart sapmasini aliniz.b.varyansini aliniz.c.median’ini aliniz.d.en kucuk degeri bulunuz.e.en buyuk degeri bulunuz

In [47]:
np.linspace(-0,1,50) 

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [48]:
np.mean(matrs)

22.5

In [50]:
np.std(matrs)

14.361406616345072

In [52]:
np.var(matrs)

206.25

In [53]:
np.median(matrs)

22.5

In [54]:
np.min(matrs)

0

In [55]:
np.max(matrs)

45